In [28]:
import numpy as np
import pandas as pd

In [29]:
# df = pd.read_csv('train.csv')
X_train = pd.read_csv('X_train_mvh.csv')
X_test = pd.read_csv('X_test_mvh.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

In [30]:
X_train.head()

   Pclass     Sex  SibSp  Parch     Fare   Age Embarked
0       1    male      0      0  28.5000  45.5        S
1       2    male      0      0  13.0000  23.0        S
2       3    male      0      0   7.9250  32.0        S
3       3    male      1      0   7.8542  26.0        S
4       3  female      4      2  31.2750   6.0        S

In [31]:
X_train['Sex'].value_counts()

Sex
male      467
female    245
Name: count, dtype: int64

In [32]:
X_train.shape

(712, 7)

In [33]:
X_train.isnull().sum()

Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Age         0
Embarked    0
dtype: int64

In [34]:
X_train.dtypes

Pclass        int64
Sex          object
SibSp         int64
Parch         int64
Fare        float64
Age         float64
Embarked     object
dtype: object

In [35]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False)

X_train_ohe = ohe.fit_transform(X_train[['Sex','Embarked']]).astype('int64')
X_test_ohe = ohe.transform(X_test[['Sex','Embarked']]).astype('int64')

In [36]:
X_train_ohe

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       ...,
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1]])

In [37]:
train_nominal_encoded_df = pd.DataFrame(X_train_ohe, 
                                        columns=ohe.get_feature_names_out(), 
                                        index=X_train.index)
test_nominal_encoded_df = pd.DataFrame(X_test_ohe, 
                                       columns=ohe.get_feature_names_out(), 
                                       index=X_test.index)
train_nominal_encoded_df

     Sex_male  Embarked_Q  Embarked_S
0           1           0           1
1           1           0           1
2           1           0           1
3           1           0           1
4           0           0           1
..        ...         ...         ...
707         0           0           1
708         1           0           1
709         1           0           1
710         0           0           1
711         1           0           1

[712 rows x 3 columns]

In [40]:
# #for one ordinal feature
# ordinal_orders = [['Mild','Strong']]
# oe = OrdinalEncoder(categories=ordinal_orders)
# X_train[['cough']] = oe.fit_transform(X_train[['cough']])
# X_test[['cough']] = oe.transform(X_test[['cough']])

# #for multiple ordinal feature
# ordinal_orders = [['Mild','Strong'],['Good','Better','Best'],['FA','BA','MA']]
# oe = OrdinalEncoder(categories=ordinal_orders)
# X_train[['cough','Review','Qualification']] = oe.fit_transform(X_train[['cough','Review','Qualification']])
# X_test[['cough','Review','Qualification']] = oe.transform(X_test[['cough','Review','Qualification']])

In [54]:
X_train = np.concatenate((train_nominal_encoded_df,),axis=1)
X_test = np.concatenate((train_nominal_encoded_df,),axis=1)
# X_train = X_train.drop(columns=['Sex','Embarked']).join(train_nominal_encoded_df)
# X_test = X_test.drop(columns=['Sex','Embarked']).join(test_nominal_encoded_df)

X_train.shape

(712, 3)

In [53]:
X_train

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [47]:

# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# y_train_le = le.fit_transform(y_train)
# y_test_le = le.transform(y_test)

## With Column Transformer

In [39]:
# from sklearn.compose import ColumnTransformer
# transformer = ColumnTransformer(transformers=[
#     ('tnf1',SimpleImputer(),['fever']),
#     ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
#     ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
# ],remainder='passthrough')

In [40]:
# X_train = transformer.fit_transform(X_train)
# X_test = transformer.transform(X_test)

In [41]:
# X_train = X_train.round().astype('int64')
# X_test = X_test.round().astype('int64')

# X_train

In [42]:
X_train.to_csv('X_train_encoded.csv',index=False)
X_test.to_csv('X_test_encoded.csv',index=False)
y_train.to_csv('y_train.csv',index=False)
y_test.to_csv('y_test.csv',index=False)

In [43]:
X_train.sample(3)

     Pclass  SibSp  Parch     Fare   Age  Sex_male  Embarked_Q  Embarked_S
96        3      0      0   8.0500  29.0         1           0           1
500       1      1      0  65.6344  54.0         0           0           0
660       3      0      0   9.0000  47.0         1           0           1